import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  buttonHome: {
    backgroundColor: '#FFFFFF',
    height: 100,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
  buttonChallenge: {
    backgroundColor: '#FFFFFF',
    height: 120,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
  buttonChallengeCheck: {
    backgroundColor: '#D8F3DC',
    height: 120,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
});
