import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  buttonHome: {
    backgroundColor: '#FFFFFF',
    height: 100,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
  buttonChallenge: {
    backgroundColor: '#FFFFFF',
    height: 120,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
  buttonChallengeCheck: {
    backgroundColor: '#D8F3DC',
    height: 120,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 25,
    flexDirection: 'row',
  },
  buttonConfig: {
    backgroundColor: '#FFFFFF',
    height: 50,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  buttonRecap: {
    backgroundColor: '#D8F3DC',
    height: 150,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 20,
  },
  buttonValidate: {
    backgroundColor: 'white',
    height: 40,
    width: 350,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#74C69D',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 20,
    textAlign: 'center',
    marginBottom: 25,
  },
});
